### ISSUE TITLE
pyprob build outside of docker does not work

### ISSUE THREAD

**Issue by karenyyng** [probprog/pyprob#8]
I tried building `pyprob` without using Docker on Cori. So far I have no success doing so.

Steps for me to install pyprob locally on Cori:
```
cori07:workspace (master)$ module load python/3.5-anaconda
cori07:workspace (master)$ conda create -n pytorchPyprob -c intel intelpython3_core python=3
(pytorchPyprob) cori07:workspace (master)$ conda install -c pytorch pytorch=0.3.0
(pytorchPyprob) cori07:workspace (master)$ git clone https://github.com/probprog/pyprob/
(pytorchPyprob) cori07:workspace (master)$ pip install -r ./pyprob/requirements.txt
(pytorchPyprob) cori07:workspace (master)$ cd ./pyprob && python setup.py install
(pytorchPyprob) cori07:workspace (master)$ cd $SCRATCH/etalumis-perf-test/workspace
(pytorchPyprob) cori07:workspace (master)$ pyprob-compile --batchPool ./batchpool --obsEmb cnn3d4c --batchSize 4 --validSize 4 --maxTraces 32
```
I get the following error:
```
(pytorchPyprob) cori07:workspace (master)$ pyprob-compile --batchPool ./batchpool --obsEmb cnn3d4c --batchSize 4 --validSize 4 --maxTraces 32
Traceback (most recent call last):
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/bin/pyprob-compile", line 11, in <module>
    load_entry_point('pyprob==0.10.0.dev10', 'console_scripts', 'pyprob-compile')()
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2598, in load_entry_point
    return ep.load()
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pyprob-0.10.0.dev10-py3.6.egg/pyprob/__init__.py", line 6, in <module>
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pyprob-0.10.0.dev10-py3.6.egg/pyprob/model.py", line 10, in <module>
  File "/global/cscratch1/sd/karenyng/py35_envs/pytorchPyprob/lib/python3.6/site-packages/pyprob-0.10.0.dev10-py3.6.egg/pyprob/comm.py", line 13, in <module>
ModuleNotFoundError: No module named 'infcomp'

```

I looked through `setup.py` it looks alright and includes `infcomp.protocol` so I am not sure why it does not import `infcomp.protocol` correctly.

**Comment by karenyyng** [comment]
reproduced the same error with the open source version of setuptools:

```
$ conda list | grep setuptools
Using Anaconda Cloud api site https://api.anaconda.org
setuptools                36.4.0                   py36_1
```

**Comment by Lezcano** [comment]
Probably not the optimal way of doing things, but I used to use this command to build pyprob locally:
```
virtualenv pyprob && cd pyprob && git clone https://github.com/probprog/pyprob && source bin/activate && cd pyprob && pip3 install http://download.pytorch.org/whl/cu75/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl && pip install torchvision && pip install -r requirements.txt && pip install .
```

**Comment by karenyyng** [comment]
@Lezcano your way of installing the python packages is perfectly fine. 
I would use the following command for creating a python 3.5 environment though.
```
virtualenv -p $(which python3.5) pyprob --distribute
```

I like to use Conda because other Intel optimized packages can be more easily installed that way. 
I will try your way of installation and report back whether if it works.

**Comment by gbaydin** [comment]
The `infcomp` module has changed significantly (it no longer exists) :).  I believe that this issue no longer applies, and I'm closing it.
